South/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import app.views as view

urlpatterns = [
	url(r'^$', view.home, name='home'),
    url(r'^Категория-(?P<category_name>[\w\-]+)$', view.category, name='category'),
    #url(r'^Категория-(?P<category_name>[\w\-]+)/Подкатегория-(?P<sub_name>[\w\-]+)$', view.sub_category, name='sub_category'),
    url(r'^Категория-(?P<category_name>[\w\-]+)/Объект-(?P<proper_name>[\w\-]+)$', view.object_detail, name='object'),
	#url(r'^blog$', view.blog, name='blog'),
    url(r'^contact$', view.contact, name='contact'),
	url(r'^about$', view.about, name='about'),
    url(r'^admin/', admin.site.urls),
] 


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class SubSection(models.Model):
    #Поразделы секций
    name = models.CharField(verbose_name=u'Название подсекции', max_length=200, default=None)
    section = models.ForeignKey('Section', on_delete=models.CASCADE, related_name='subsection')
    slug = models.CharField(verbose_name=u'Ссылочное имя', max_length=200, editable=False, default=None)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.name:
            self.slug = slugify(self.name, allow_unicode=True)
        super(SubSection, self).save(*args, **kwargs)

    class Meta:
        verbose_name=u'Подсекции'
        verbose_name_plural=u'Подсекции'

class Section(models.Model):
    #Секции недвижмости
    name = models.CharField(verbose_name=u'Название секций', max_length=200)
    slug = models.CharField(verbose_name=u'Ссылочное имя', max_length=200, editable=False, default=None)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.name:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Section, self).save(*args, **kwargs)

    class Meta:
        verbose_name=u'Секция'
        verbose_name_plural=u'Секция'

def custom_directory(instance, filename):
    return 'app/images/{0}/{1}/{2}'.format(instance.property.section.slug, instance.property.slug, filename)

class PropertyPhoto(models.Model):
    photo = models.ImageField(upload_to=custom_directory, default='media/app/images/None/no_image.png', max_length=200)
    property = models.ForeignKey('Property', on_delete=models.CASCADE)


class Property(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    section = models.ForeignKey('Section', on_delete=models.CASCADE, related_name='section_property')
    sub = models.ForeignKey('SubSection', on_delete=models.CASCADE, related_name='sub_property', blank=True, null=True)
    slug = models.CharField(verbose_name=u'Ссылочное имя', max_length=200, editable=False, default=None)
    name = models.CharField(verbose_name=u'Краткое описание', max_length=200)
    description = models.TextField(verbose_name=u'Полное описание', default='Информация не предоставлена')
    cadastre = models.CharField(verbose_name=u'Кадастровый номер', max_length=200, default='Информация не предоставлена', unique=True)
    yardage = models.CharField(verbose_name=u'Площадь', max_length=200, default='Информация не предоставлена')
    price = models.CharField(verbose_name=u'Цена', max_length=200, default='Информация не предоставлена')
    avito_url = models.URLField(verbose_name=u'Ссылка на авито', max_length=200, blank=True)
    PropertyPhoto = None

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.name:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Property, self).save(*args, **kwargs)

    class Meta:
        ordering = ('created',)
        verbose_name=u'Недвижимость'
        verbose_name_plural=u'Недвижимость'

blog/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from datetime import datetime
from app.models import Property, Section, PropertyPhoto, SubSection


# Create your views here.
def home(request):
	property = Property.objects.all()
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys
		}
		)

def category(request, category_name):
	property = Property.objects.filter(section__slug=category_name)
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'active_category': True
		}
		)
"""def sub_category(request, category_name, sub_name):
	property = Property.objects.filter(section__slug=category_name, sub__slug=sub_name)
	sub_categorys = SubSection.objects.filter(section__slug=category_name)
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'sub_categorys': sub_categorys,
		'active_sub_category': True
		}
		)
	"""
def object_detail(request, category_name, proper_name):
	property = Property.objects.filter(slug=proper_name)
	categorys = Section.objects.all()
	photo = PropertyPhoto.objects.filter(property__slug=proper_name)
	return render(
		request,
		'app/objects.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'photo': photo,
		'active_object': True
		}
		)

def contact (request):
	return render(
		request,
		'app/contact.html',
		{
		'year':datetime.now().year,
		}
		)

def about (request):
	return render(
		request,
		'app/about.html',
		{
		'year':datetime.now().year,
		}
		)

blog/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.shortcuts import render

# Create your views here.

views.py
from django.shortcuts import render
from datetime import datetime
from app.models import Property, Section, PropertyPhoto, SubSection


# Create your views here.
def home(request):
	property = Property.objects.all()
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys
		}
		)

def category(request, category_name):
	property = Property.objects.filter(section__slug=category_name)
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'active_category': True
		}
		)
"""def sub_category(request, category_name, sub_name):
	property = Property.objects.filter(section__slug=category_name, sub__slug=sub_name)
	sub_categorys = SubSection.objects.filter(section__slug=category_name)
	categorys = Section.objects.all()
	return render(
		request,
		'app/index.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'sub_categorys': sub_categorys,
		'active_sub_category': True
		}
		)
	"""
def object_detail(request, category_name, proper_name):
	property = Property.objects.filter(slug=proper_name)
	categorys = Section.objects.all()
	photo = PropertyPhoto.objects.filter(property__slug=proper_name)
	return render(
		request,
		'app/objects.html',
		{
		'year':datetime.now().year,
		'property': property,
		'categorys': categorys,
		'photo': photo,
		'active_object': True
		}
		)

def contact (request):
	return render(
		request,
		'app/contact.html',
		{
		'year':datetime.now().year,
		}
		)

def about (request):
	return render(
		request,
		'app/about.html',
		{
		'year':datetime.now().year,
		}
		)

app/templates/app/about (2).html
{% extends 'app/layout.html' %} {% block content %}
<div class="container">
  <div class="text_contact_main">
    <h1>Доброго времени суток!</h1>
    <br>
    <p>Добро пожаловать на сайт компании Земля-Юга.РФ</p>
    <br>
  </div>
  <div class="main_text">
    <p>Наша команда будет рада Вам помочь реализовать Ваши мечты о тихом, экологически чистом земельном участке, где будет построен
      дом Вашей мечты!</p>
    <br>
    <p>Для Вас представлен раздел "Предложения", в котором Вы можете просмтотреть все объявления</p>
  </div>
</div>
{% endblock %}

app/templates/app/about.html
{% extends 'app/layout.html' %} {% block content %}
<div class="container">
  <div class="text_contact_main">
    <h1>Доброго времени суток!</h1>
    <br>
    <p>Добро пожаловать на сайт компании Земля-Юга.РФ</p>
    <br>
  </div>
  <div class="main_text">
    <p>Наша команда будет рада Вам помочь реализовать Ваши мечты о тихом, экологически чистом земельном участке, где будет построен
      дом Вашей мечты!</p>
    <br>
    <p>Для Вас представлен раздел "Предложения", в котором Вы можете просмтотреть все объявления</p>
  </div>
</div>
{% endblock %}

app/templates/app/contact (2).html
{% extends 'app/layout.html' %} {% block content %}
<div class="container">
  <div class="text_contact">
    <h1>Контакты</h1>
    <br>

    <p>350062, Российская Федерация, Южный федеральный округ, Краснодарский край, город Краснодар, улица Атарбекова, 1
    </p>
    <br>

    <p>Телефон +7 (988) 246-10-10</p>
    <br>

    <p>E-mail: 89882461010@mail.ru</p>
    <br/>
    <br/>
  </div>
 <!-- <p class="text_form">Здесь Вы можете оставить нам информацию</p>

  <form method="POST" id="feedback-form">
    Как к Вам обращаться:
    <input type="text" name="nameFF" required placeholder="Иванов Иван Иванович" x-autocompletetype="name"> Email для связи:
    <input type="email" name="contactFF" required placeholder="example@mail.com" x-autocompletetype="email"> Ваше сообщение:
    <textarea name="messageFF" required placeholder="Ваш текст сообщения" rows="5"></textarea>
    <br/>
    <input type="submit" value="Отправить">
  </form>-->
</div>
{% endblock %}

app/templates/app/contact.html
{% extends 'app/layout.html' %} {% block content %}
<div class="container">
  <div class="text_contact">
    <h1>Контакты</h1>
    <br>

    <p>350062, Российская Федерация, Южный федеральный округ, Краснодарский край, город Краснодар, улица Атарбекова, 1
    </p>
    <br>

    <p>Телефон +7 (988) 246-10-10</p>
    <br>

    <p>E-mail: 89882461010@mail.ru</p>
    <br/>
    <br/>
  </div>
 <!-- <p class="text_form">Здесь Вы можете оставить нам информацию</p>

  <form method="POST" id="feedback-form">
    Как к Вам обращаться:
    <input type="text" name="nameFF" required placeholder="Иванов Иван Иванович" x-autocompletetype="name"> Email для связи:
    <input type="email" name="contactFF" required placeholder="example@mail.com" x-autocompletetype="email"> Ваше сообщение:
    <textarea name="messageFF" required placeholder="Ваш текст сообщения" rows="5"></textarea>
    <br/>
    <input type="submit" value="Отправить">
  </form>-->
</div>
{% endblock %}

app/templates/app/index (2).html
{% extends 'app/layout.html' %} 
{% block content %}
    <div class="group">
        {% for proper in property %}
        <div class="single-pen">
            <a href="{% url 'object' proper.section.slug proper.slug %}" class="cover-link"></a>
            {% with photo=proper.propertyphoto_set.all|first %}
            <img src="{{photo.photo.url}}" class="object">
            {% endwith %}
            <div class="meta">
                <p>{{proper.name}}</p>
                <p>{{proper.price}}</p>
                <p>{{proper.country}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/layout.html' %} 
{% block content %}
    <div class="group">
        {% for proper in property %}
        <div class="single-pen">
            <a href="{% url 'object' proper.section.slug proper.slug %}" class="cover-link"></a>
            {% with photo=proper.propertyphoto_set.all|first %}
            <img src="{{photo.photo.url}}" class="object">
            {% endwith %}
            <div class="meta">
                <p>{{proper.name}}</p>
                <p>{{proper.price}}</p>
                <p>{{proper.country}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/app/layout (2).html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% url 'about' as about %}
{% url 'home' as home %}
{% url 'contact' as contact %}
{% url 'category' as category %}
{% url 'sub_category' as sub_category %}
{% url 'object' as object %}
{% load highlights %}
{% load counter %}


<head>
  <link rel="shortcut icon" href="{% static 'app/images/fav.ico' %}" type="image/x-icon">
  <link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css'>
  <title>Земля-Юга.РФ</title>
  <link rel="stylesheet" href="{% static 'app/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/feedback.css' %}">
</head>

<body>
  <script type="text/javascript" src="{% static 'app/script/galleryjs.js' %}" defer ></script>
  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46170443-1', 'auto');
    ga('send', 'pageview');
  </script>
  <div class="header">
    <a href="{% url 'home' %}">
      <img src="{% static 'app/images/logo.png' %}" class="header_logo" alt="Земля-Юга.РФ">
    </a>
    <img src="{% static 'app/images/phone.png' %}" class="header_phone" alt="+7(988) 246-10-10">
  </div>
  <div id="mainmenu">
    <ul>
      <li {% if request.path == about %} class="current-menu-item" {% endif %}><a href="{% url 'about'%}">О нас</a></li>
      <li {% if request.path == home %} class="current-menu-item" {% elif active_object %} class="current-menu-item" {% elif active_category %} class="current-menu-item" {% endif %}><a href="{% url 'home' %}">Предложения</a></li>
      <li {% if request.path == contact %} class="current-menu-item" {% endif %}><a href="{% url 'contact' %}">Контакты</a></li>
    </ul>
  </div>
  <div class="background_menu">
    <blockquote>
      <p class="text_header">"Покупайте землю, её больше не производят."
        <cite>Марк Твен</cite>
      </p>
    </blockquote>
  </div>
  <div class="container">
    <div class="production">
            <h1><a href="{% url 'home' %}" class="decoration2">Категории:</a></h1>
            <ul>
                {% for category in categorys %}
                    <li class='decoration2' ><h3><a class="decoration2 {% active category.name %}" href="{% url 'category' category.slug %}">{{category.name}}({% counter category %})</a></h3></li>
                        <ul>
                        {% for sub in sub_categorys %}
                        {% if sub.section.id == category.id %}
                            <li class="decoration3" ><h4><a class="decoration3" href="#">{{sub.name}}({% counter sub %})</a></h4></li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                {% endfor %}
            </ul>
        </div>
  {% block content %} {% endblock %}
  </div>
  <div id="footer">
    <a href="{% url 'home' %}" class="decoration">&copy; Земля-Юга {{year}}</a>
    <a href="http://alexeykhabibulin.ru/" class="developer">Разработчик Алексей Хабибулин</a>
  </div>

</body>

</html>

app/templates/app/layout.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% url 'about' as about %}
{% url 'home' as home %}
{% url 'contact' as contact %}
{% url 'category' as category %}
{% url 'sub_category' as sub_category %}
{% url 'object' as object %}
{% load highlights %}
{% load counter %}


<head>
  <link rel="shortcut icon" href="{% static 'app/images/fav.ico' %}" type="image/x-icon">
  <link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css'>
  <title>Земля-Юга.РФ</title>
  <link rel="stylesheet" href="{% static 'app/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/feedback.css' %}">
</head>

<body>
  <script type="text/javascript" src="{% static 'app/script/galleryjs.js' %}" defer ></script>
  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-46170443-1', 'auto');
    ga('send', 'pageview');
  </script>
  <div class="header">
    <a href="{% url 'home' %}">
      <img src="{% static 'app/images/logo.png' %}" class="header_logo" alt="Земля-Юга.РФ">
    </a>
    <img src="{% static 'app/images/phone.png' %}" class="header_phone" alt="+7(988) 246-10-10">
  </div>
  <div id="mainmenu">
    <ul>
      <li {% if request.path == about %} class="current-menu-item" {% endif %}><a href="{% url 'about'%}">О нас</a></li>
      <li {% if request.path == home %} class="current-menu-item" {% elif active_object %} class="current-menu-item" {% elif active_category %} class="current-menu-item" {% endif %}><a href="{% url 'home' %}">Предложения</a></li>
      <li {% if request.path == contact %} class="current-menu-item" {% endif %}><a href="{% url 'contact' %}">Контакты</a></li>
    </ul>
  </div>
  <div class="background_menu">
    <blockquote>
      <p class="text_header">"Покупайте землю, её больше не производят."
        <cite>Марк Твен</cite>
      </p>
    </blockquote>
  </div>
  <div class="container">
    <div class="production">
            <h1><a href="{% url 'home' %}" class="decoration2">Категории:</a></h1>
            <ul>
                {% for category in categorys %}
                    <li class='decoration2' ><h3><a class="decoration2 {% active category.name %}" href="{% url 'category' category.slug %}">{{category.name}}({% counter category %})</a></h3></li>
                        <ul>
                        {% for sub in sub_categorys %}
                        {% if sub.section.id == category.id %}
                            <li class="decoration3" ><h4><a class="decoration3" href="#">{{sub.name}}({% counter sub %})</a></h4></li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                {% endfor %}
            </ul>
        </div>
  {% block content %} {% endblock %}
  </div>
  <div id="footer">
    <a href="{% url 'home' %}" class="decoration">&copy; Земля-Юга {{year}}</a>
    <a href="http://alexeykhabibulin.ru/" class="developer">Разработчик Алексей Хабибулин</a>
  </div>

</body>

</html>

app/templates/app/objects (2).html
{% extends 'app/layout.html' %} 
{% block content %}
    <div class="detail-object">
        <div class="main-info">
            {% for proper in property %}
            {% with photo=proper.propertyphoto_set.all|first %}
            <img src="{{photo.photo.url}}" id="LargImg">
            {% endwith %}
            <ul id="thumbgallery">
                {% for phot in photo %}
                <li class="thumb"><a href="{{phot.photo.url}}"><img src="{{phot.photo.url}}" id="thumb"></a></li>
                {% endfor %}
            </ul>
            <p>Название: </p><p>{{proper.name}}</p>
            <div class="divider"></div>
            <p>Описание: </p><p>{{proper.description}}</p>
            <div class="divider"></div>
        </div>
        <div class="additions">
            <p>Кадастровый номер: </p><p>{{proper.cadastre}}</p>
            <div class="divider"></div>
            <p>Площадь: </p><p>{{proper.yardage}}</p>
            <div class="divider"></div>
            <p>Цена: </p><p>{{proper.price}}</p>
            <div class="divider"></div>
            {% if proper.avito_url %}
            <a href="{{proper.avito_url}}"><p>Предложение на авито</p></a>
            {% endif %}
        </div>
            {% endfor %}
    </div>
{% endblock %}

app/templates/app/objects.html
{% extends 'app/layout.html' %} 
{% block content %}
    <div class="detail-object">
        <div class="main-info">
            {% for proper in property %}
            {% with photo=proper.propertyphoto_set.all|first %}
            <img src="{{photo.photo.url}}" id="LargImg">
            {% endwith %}
            <ul id="thumbgallery">
                {% for phot in photo %}
                <li class="thumb"><a href="{{phot.photo.url}}"><img src="{{phot.photo.url}}" id="thumb"></a></li>
                {% endfor %}
            </ul>
            <p>Название: </p><p>{{proper.name}}</p>
            <div class="divider"></div>
            <p>Описание: </p><p>{{proper.description}}</p>
            <div class="divider"></div>
        </div>
        <div class="additions">
            <p>Кадастровый номер: </p><p>{{proper.cadastre}}</p>
            <div class="divider"></div>
            <p>Площадь: </p><p>{{proper.yardage}}</p>
            <div class="divider"></div>
            <p>Цена: </p><p>{{proper.price}}</p>
            <div class="divider"></div>
            {% if proper.avito_url %}
            <a href="{{proper.avito_url}}"><p>Предложение на авито</p></a>
            {% endif %}
        </div>
            {% endfor %}
    </div>
{% endblock %}